// Generated by work/import_impact_decals.py from MCV decals_subrect.txt.
// Standalone materials preserve original textures and decal scale.
MCV.SurfaceDecals = {
    asphalt = {"mcv/decals/asphalt/asphalt1", "mcv/decals/asphalt/asphalt2", "mcv/decals/asphalt/asphalt3", "mcv/decals/asphalt/asphalt4"},
    brick = {"mcv/decals/brick/brick1", "mcv/decals/brick/brick2", "mcv/decals/brick/brick3", "mcv/decals/brick/brick4"},
    cardboard = {"mcv/decals/cardboard/cardboard1", "mcv/decals/cardboard/cardboard2", "mcv/decals/cardboard/cardboard3", "mcv/decals/cardboard/cardboard4"},
    carpet = {"mcv/decals/dirt/dirt1", "mcv/decals/dirt/dirt2", "mcv/decals/dirt/dirt3", "mcv/decals/dirt/dirt4"},
    computer = {"mcv/decals/computer/computer1", "mcv/decals/computer/computer2", "mcv/decals/computer/computer3", "mcv/decals/computer/computer4"},
    concrete = {"mcv/decals/concrete/concrete1", "mcv/decals/concrete/concrete2", "mcv/decals/concrete/concrete3", "mcv/decals/concrete/concrete4"},
    dirt = {"mcv/decals/dirt/dirt1", "mcv/decals/dirt/dirt2", "mcv/decals/dirt/dirt3", "mcv/decals/dirt/dirt4"},
    glass = {"mcv/decals/glass/shot1", "mcv/decals/glass/shot2", "mcv/decals/glass/shot3", "mcv/decals/glass/shot4"},
    grass = {"mcv/decals/dirt/dirt1", "mcv/decals/dirt/dirt2", "mcv/decals/dirt/dirt3", "mcv/decals/dirt/dirt4"},
    leaves = {"mcv/decals/dirt/dirt1", "mcv/decals/dirt/dirt2", "mcv/decals/dirt/dirt3", "mcv/decals/dirt/dirt4"},
    metal = {"mcv/decals/metal/metal01", "mcv/decals/metal/metal02", "mcv/decals/metal/metal03", "mcv/decals/metal/metal04"},
    mud = {"mcv/decals/dirt/dirt1", "mcv/decals/dirt/dirt2", "mcv/decals/dirt/dirt3", "mcv/decals/dirt/dirt4"},
    plaster = {"mcv/decals/plaster/plaster01", "mcv/decals/plaster/plaster02", "mcv/decals/plaster/plaster03", "mcv/decals/plaster/plaster04"},
    plastic = {"mcv/decals/computer/computer1", "mcv/decals/computer/computer2", "mcv/decals/computer/computer3", "mcv/decals/computer/computer4"},
    rock = {"mcv/decals/rock/rock01", "mcv/decals/rock/rock02", "mcv/decals/rock/rock03", "mcv/decals/rock/rock04"},
    rubber = {"mcv/decals/rubber/rubber1", "mcv/decals/rubber/rubber2", "mcv/decals/rubber/rubber3", "mcv/decals/rubber/rubber4"},
    sand = {"mcv/decals/dirt/dirt1", "mcv/decals/dirt/dirt2", "mcv/decals/dirt/dirt3", "mcv/decals/dirt/dirt4"},
    sheetrock = {"mcv/decals/sheetrock/sheetrock1", "mcv/decals/sheetrock/sheetrock2", "mcv/decals/sheetrock/sheetrock3", "mcv/decals/sheetrock/sheetrock4"},
    snow = {"mcv/decals/dirt/dirt1", "mcv/decals/dirt/dirt2", "mcv/decals/dirt/dirt3", "mcv/decals/dirt/dirt4"},
    tile = {"mcv/decals/tile/tile1", "mcv/decals/tile/tile2", "mcv/decals/tile/tile3", "mcv/decals/tile/tile4", "mcv/decals/tile/tile5", "mcv/decals/tile/tile6"},
    upholstery = {"mcv/decals/upholstery/upholstery1", "mcv/decals/upholstery/upholstery2", "mcv/decals/upholstery/upholstery3", "mcv/decals/upholstery/upholstery4"},
    vent = {"mcv/decals/metal/metal01", "mcv/decals/metal/metal02", "mcv/decals/metal/metal03", "mcv/decals/metal/metal04"},
    wood = {"mcv/decals/wood/wood1", "mcv/decals/wood/wood2", "mcv/decals/wood/wood3", "mcv/decals/wood/wood4"},
}

for family, materials in pairs(MCV.SurfaceDecals) do
    game.AddDecal("MCV.Impact." .. family, materials)
end
