SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_dual_mac10.txt

// Names and basic information
SWEP.PrintName = "MAC10"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Machine Pistols"
SWEP.Caliber = "9x19mm"

SWEP.Slot = 1
SWEP.HoldType = "pistol"
SWEP.AimHoldType = "revolver"
SWEP.SprintHoldType = "normal"

SWEP.ViewModel = "models/weapons/mcv/v_dual_mac10.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_dual_mac10.mdl"

SWEP.BodyGroups = ""

// Stats

SWEP.DamageGeneric = 26
SWEP.DamageHeadMultiplier = 2.4
SWEP.DamageChestMultiplier = 1.3
SWEP.DamageStomachMultiplier = 1.2
SWEP.DamageLegMultiplier = 0.8
SWEP.DamageArmMultiplier = 0.75

SWEP.Num = 1

SWEP.RangeModifier = 0.78

SWEP.Firemodes = {
    MCV.FIREMODE_AUTO,
    MCV.FIREMODE_SEMI
}

SWEP.LastShotAnimation = true

// View slide from recoil
SWEP.ViewSlideRecoilUp = 1.48
SWEP.ViewSlideRecoilRight = 0.8

SWEP.ViewSlideRecoilIronsightUp = 0.74
SWEP.ViewSlideRecoilIronsightRight = 0.32

SWEP.RecoilPushbackValue = 1.5

// Camera shake from recoil
SWEP.ShakeScale = 0.6
SWEP.ShakeFreq = 60
SWEP.ShakeDuration = 0.3

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 1.1
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -0.25

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(0.06, -4, 0) -- TODO tune (game: forward -6 right 0 up 0)
SWEP.IronsightAng = Angle(0.25, 0.1, 0) -- TODO tune

SWEP.CustomPos = Vector(0, -2, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 20
SWEP.SpreadIronsighted = 4.2

SWEP.FireRate = 1250 // in rounds per minute

SWEP.CrosshairMinDistance = 4
SWEP.CrosshairDeltaDistance = 4

SWEP.WeaponWeight = 4.84

SWEP.Primary.Ammo = "pistol"
SWEP.Primary.ClipSize = 64
SWEP.Primary.Chamber = 0
SWEP.Primary.DefaultClip = 192
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 15

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 0.85
SWEP.ProneSpreadMultiplier = 0.75
SWEP.StandMoveSpreadMultiplier = 1.25
SWEP.SneakMoveSpreadMultiplier = 1.15
SWEP.CrouchMoveSpreadMultiplier = 1.15
SWEP.JumpSpreadMultiplier = 1.7

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = false

// Penetration
SWEP.MetalPenetrationDepth = 5
SWEP.GlassPenetrationDepth = 11
SWEP.ConcretePenetrationDepth = 7
SWEP.WoodPenetrationDepth = 15
SWEP.OtherPenetrationDepth = 9

SWEP.MetalDamageModifier = 1.7
SWEP.GlassDamageModifier = 1.3
SWEP.ConcreteDamageModifier = 1.9
SWEP.WoodDamageModifier = 1.4
SWEP.OtherDamageModifier = 1.4

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_MAC10.Single"
SWEP.SoundDoubleShot = ""
SWEP.SoundReload = ""
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick_MachinePistol"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_04"

// Particles
SWEP.MuzzleParticle = "muzzleflash_pistol"
SWEP.MuzzleParticleSmoke = ""
SWEP.MuzzleParticleIronsighted = "muzzleflash_pistol"
SWEP.MuzzleParticleIronsightedSmoke = ""

SWEP.MuzzleParticle3rdPerson = "muzzleflash_pistol"

SWEP.EjectBrassType = 12
SWEP.EjectBrassTrail = "shellsmoke"
SWEP.EjectBrassParticle = "port_smoke"

SWEP.TracerParticle = "tracer"

SWEP.TracerRandomness = 6
SWEP.TracerFrequency = 3
