SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_baby_browning.txt

// Names and basic information
SWEP.PrintName = "Baby Browning"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Belgium"
SWEP.SubCategory = "Pistols"
SWEP.Caliber = ".25 ACP"

SWEP.Slot = 1
SWEP.HoldType = "pistol"
SWEP.AimHoldType = "revolver"
SWEP.SprintHoldType = "normal"

SWEP.ViewModel = "models/weapons/mcv/v_babybrowning.mdl"
SWEP.ViewModelAkimbo = "models/weapons/mcv/v_dual_babybrowning.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_babybrowning.mdl"

SWEP.BodyGroups = ""

// Stats

SWEP.DamageGeneric = 17
SWEP.DamageHeadMultiplier = 5
SWEP.DamageChestMultiplier = 1.7
SWEP.DamageStomachMultiplier = 1.6
SWEP.DamageLegMultiplier = 1.2
SWEP.DamageArmMultiplier = 1.1

SWEP.Num = 1

SWEP.RangeModifier = 0.67

SWEP.Firemodes = {
    MCV.FIREMODE_SEMI
}

SWEP.LastShotAnimation = false
SWEP.NoEjectOnShoot = false

// View slide from recoil
SWEP.ViewSlideRecoilUp = 1.08
SWEP.ViewSlideRecoilRight = 0.44

SWEP.ViewSlideRecoilIronsightUp = 0.8
SWEP.ViewSlideRecoilIronsightRight = 0.32

SWEP.RecoilPushbackValue = 1.5

// Camera shake from recoil
SWEP.ShakeScale = 0.75
SWEP.ShakeFreq = 50
SWEP.ShakeDuration = 0.35

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 0.85
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -1

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(0.07, -4, 0.1)
SWEP.IronsightAng = Angle(0.3, -0.28, 0)

SWEP.CustomPos = Vector(0, -2, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 5
SWEP.SpreadIronsighted = 2

SWEP.FireRate = 250 // in rounds per minute

SWEP.CrosshairMinDistance = 4
SWEP.CrosshairDeltaDistance = 4

SWEP.WeaponWeight = 0

SWEP.Primary.Ammo = "pistol"
SWEP.Primary.ClipSize = 6
SWEP.Primary.Chamber = 1
SWEP.Primary.DefaultClip = 12
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 22

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 0.95
SWEP.ProneSpreadMultiplier = 0.9
SWEP.StandMoveSpreadMultiplier = 1.1
SWEP.SneakMoveSpreadMultiplier = 1.05
SWEP.CrouchMoveSpreadMultiplier = 1
SWEP.JumpSpreadMultiplier = 1.25

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false
SWEP.HasAkimbo = true

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = false

// Penetration
SWEP.MetalPenetrationDepth = 4
SWEP.GlassPenetrationDepth = 10
SWEP.ConcretePenetrationDepth = 6
SWEP.WoodPenetrationDepth = 14
SWEP.OtherPenetrationDepth = 8

SWEP.MetalDamageModifier = 1.8
SWEP.GlassDamageModifier = 1.4
SWEP.ConcreteDamageModifier = 2
SWEP.WoodDamageModifier = 1.5
SWEP.OtherDamageModifier = 1.5

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_BabyBrowning.Single"
SWEP.SoundDoubleShot = ""
SWEP.SoundReload = ""
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick_Pistol"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_03"

// Particles (the game's own systems; particles/*.pcf and their materials ship with the addon)
SWEP.MuzzleParticle = "vietnam_muzzleflash_pistol_type3_fp"
SWEP.MuzzleParticleSmoke = "vietnam_muzzleflash_pistol_type1_fp_smoke"
SWEP.MuzzleParticleIronsighted = "vietnam_muzzleflash_pistol_type3_fp_is"
SWEP.MuzzleParticleIronsightedSmoke = "vietnam_muzzleflash_pistol_type1_fp_is_smoke"

SWEP.MuzzleParticle3rdPerson = "vietnam_muzzleflash_pistol_type3_tp"

SWEP.EjectBrassType = 15
SWEP.EjectBrassTrail = "vietnam_weaponeffect_shelleject_trail"
SWEP.EjectBrassParticle = "vietnam_weaponeffect_shelleject_side"

SWEP.TracerParticle = "vietnam_tracer_pistol_primary"

SWEP.TracerRandomness = 6
SWEP.TracerFrequency = 2

SWEP.IconOverride = "entities/mcv_baby_browning.png"
