SWEP.Base = "mcv_melee"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_ak47_bayonet.txt

// Names and basic information
SWEP.PrintName = "6H2 Bayonet"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Soviet Union"
SWEP.SubCategory = "Melee"

SWEP.Slot = 0

SWEP.ViewModel = "models/weapons/mcv/v_ak47_bayonet.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_ak47_bayonet.mdl"


SWEP.DamageGeneric = 35
SWEP.DamageGenericAlt = 55
SWEP.MeleeRange = 32
SWEP.MeleeRangeAlt = 48
SWEP.SlashRate = 150

SWEP.CanThrow = true

SWEP.SoundHitFlesh = "MCV_Weapon_AK47_Bayonet.Stab"
SWEP.SoundHitWorld = "MCV_Weapon_AK47_Bayonet.Hit"
SWEP.SoundThrustFlesh = "MCV_Weapon_AK47_Bayonet.ThrustStab"
SWEP.SoundThrustWorld = "MCV_Weapon_AK47_Bayonet.ThrustHit"

SWEP.WeaponWeight = 0
