SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_dual_type14.txt

// Names and basic information
SWEP.PrintName = "TYPE14"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Empire of Japan"
SWEP.SubCategory = "Pistols"
SWEP.Caliber = "9x18mm"

SWEP.Slot = 1
SWEP.HoldType = "pistol"
SWEP.AimHoldType = "revolver"
SWEP.SprintHoldType = "normal"

SWEP.ViewModel = "models/weapons/mcv/v_dual_type14.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_dual_type14.mdl"

SWEP.BodyGroups = ""

// Stats

SWEP.DamageGeneric = 36
SWEP.DamageHeadMultiplier = 2.6
SWEP.DamageChestMultiplier = 1.7
SWEP.DamageStomachMultiplier = 1.6
SWEP.DamageLegMultiplier = 1.1
SWEP.DamageArmMultiplier = 1.05

SWEP.Num = 1

SWEP.RangeModifier = 0.82

SWEP.Firemodes = {
    MCV.FIREMODE_SEMI
}

SWEP.LastShotAnimation = true

// View slide from recoil
SWEP.ViewSlideRecoilUp = 1.43
SWEP.ViewSlideRecoilRight = 0.42

SWEP.ViewSlideRecoilIronsightUp = 0.65
SWEP.ViewSlideRecoilIronsightRight = 0.22

SWEP.RecoilPushbackValue = 1.5

// Camera shake from recoil
SWEP.ShakeScale = 0.75
SWEP.ShakeFreq = 50
SWEP.ShakeDuration = 0.35

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 1.3
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -1

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(0.06, -4, 0) -- TODO tune (game: forward -5 right 0 up 0)
SWEP.IronsightAng = Angle(0.25, 0.1, 0) -- TODO tune

SWEP.CustomPos = Vector(0, -2, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 8.3
SWEP.SpreadIronsighted = 4.65

SWEP.FireRate = 300 // in rounds per minute

SWEP.CrosshairMinDistance = 4
SWEP.CrosshairDeltaDistance = 4

SWEP.WeaponWeight = 0.737

SWEP.Primary.Ammo = "pistol"
SWEP.Primary.ClipSize = 16
SWEP.Primary.Chamber = 0
SWEP.Primary.DefaultClip = 32
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 15

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 0.8
SWEP.ProneSpreadMultiplier = 0.75
SWEP.StandMoveSpreadMultiplier = 1.2
SWEP.SneakMoveSpreadMultiplier = 1.1
SWEP.CrouchMoveSpreadMultiplier = 1.15
SWEP.JumpSpreadMultiplier = 1.35

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = false

// Penetration
SWEP.MetalPenetrationDepth = 5
SWEP.GlassPenetrationDepth = 11
SWEP.ConcretePenetrationDepth = 7
SWEP.WoodPenetrationDepth = 15
SWEP.OtherPenetrationDepth = 9

SWEP.MetalDamageModifier = 1.7
SWEP.GlassDamageModifier = 1.3
SWEP.ConcreteDamageModifier = 1.9
SWEP.WoodDamageModifier = 1.4
SWEP.OtherDamageModifier = 1.4

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_Type14.Single"
SWEP.SoundDoubleShot = ""
SWEP.SoundReload = ""
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick_Pistol"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_05"

// Particles
SWEP.MuzzleParticle = "muzzleflash_pistol"
SWEP.MuzzleParticleSmoke = ""
SWEP.MuzzleParticleIronsighted = "muzzleflash_pistol"
SWEP.MuzzleParticleIronsightedSmoke = ""

SWEP.MuzzleParticle3rdPerson = "muzzleflash_pistol"

SWEP.EjectBrassType = 11
SWEP.EjectBrassTrail = "shellsmoke"
SWEP.EjectBrassParticle = "port_smoke"

SWEP.TracerParticle = "tracer"

SWEP.TracerRandomness = 6
SWEP.TracerFrequency = 2
