SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_rp46.txt

// Names and basic information
SWEP.PrintName = "RP-46"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Soviet Union"
SWEP.SubCategory = "Light-Machine Guns"
SWEP.Caliber = "7.62x54mmR"

SWEP.Slot = 3

SWEP.ViewModel = "models/weapons/mcv/v_rp46.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_rp46.mdl"

SWEP.BodyGroups = ""

SWEP.BulletBodygroups = {
    [1] = {1, 1},
    [2] = {2, 1},
    [3] = {3, 1},
    [4] = {4, 1},
    [5] = {5, 1},
    [6] = {6, 1},
    [7] = {7, 1},
    [8] = {8, 1},
    [9] = {9, 1},
    [10] = {10, 1},
    [11] = {11, 1},
    [12] = {12, 1},
    [13] = {13, 1},
}

// Stats

SWEP.DamageGeneric = 45
SWEP.DamageHeadMultiplier = 2.7
SWEP.DamageChestMultiplier = 1.4
SWEP.DamageStomachMultiplier = 1.35
SWEP.DamageLegMultiplier = 0.9
SWEP.DamageArmMultiplier = 0.85

SWEP.Num = 1

SWEP.RangeModifier = 0.975

SWEP.Firemodes = {
    MCV.FIREMODE_AUTO
}

SWEP.LastShotAnimation = false
SWEP.NoEjectOnShoot = false

// View slide from recoil
SWEP.ViewSlideRecoilUp = 4
SWEP.ViewSlideRecoilRight = 2

SWEP.ViewSlideRecoilIronsightUp = 3.2
SWEP.ViewSlideRecoilIronsightRight = 1.6

SWEP.RecoilPushbackValue = 1.5

// Camera shake from recoil
SWEP.ShakeScale = 0.5
SWEP.ShakeFreq = 50
SWEP.ShakeDuration = 0.3

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 1.0
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -0.25

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(0.055, -4, 0)
SWEP.IronsightAng = Angle(0.2, 0, 0)

SWEP.CustomPos = Vector(0, -2, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 15
SWEP.SpreadIronsighted = 5

SWEP.FireRate = 600 // in rounds per minute

SWEP.CrosshairMinDistance = 4
SWEP.CrosshairDeltaDistance = 4

SWEP.WeaponWeight = 13

SWEP.Primary.Ammo = "ar2"
SWEP.Primary.ClipSize = 125
SWEP.Primary.Chamber = 0
SWEP.Primary.DefaultClip = 250
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 50

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 0.6
SWEP.ProneSpreadMultiplier = 0.5
SWEP.StandMoveSpreadMultiplier = 2
SWEP.SneakMoveSpreadMultiplier = 1.9
SWEP.CrouchMoveSpreadMultiplier = 1.8
SWEP.JumpSpreadMultiplier = 3

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = true
SWEP.SpreadBipod = 3.5

// Penetration
SWEP.MetalPenetrationDepth = 10
SWEP.GlassPenetrationDepth = 16
SWEP.ConcretePenetrationDepth = 12
SWEP.WoodPenetrationDepth = 20
SWEP.OtherPenetrationDepth = 14

SWEP.MetalDamageModifier = 1.5
SWEP.GlassDamageModifier = 1.1
SWEP.ConcreteDamageModifier = 1.7
SWEP.WoodDamageModifier = 1.2
SWEP.OtherDamageModifier = 1.2

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_DP28.Single"
SWEP.SoundDoubleShot = ""
SWEP.SoundReload = ""
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick_LMG"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_08"

// Particles (the game's own systems; particles/*.pcf and their materials ship with the addon)
SWEP.MuzzleParticle = "vietnam_muzzleflash_machinegun_type4_fp"
SWEP.MuzzleParticleSmoke = "vietnam_muzzleflash_machinegun_type4_fp_smoke"
SWEP.MuzzleParticleIronsighted = "vietnam_muzzleflash_machinegun_type4_fp_is"
SWEP.MuzzleParticleIronsightedSmoke = "vietnam_muzzleflash_machinegun_type4_fp_is_smoke"

SWEP.MuzzleParticle3rdPerson = "vietnam_muzzleflash_machinegun_type4_tp"

SWEP.EjectBrassType = 8
SWEP.EjectBrassTrail = "vietnam_weaponeffect_shelleject_trail"
SWEP.EjectBrassParticle = "vietnam_weaponeffect_shelleject_side_mg_rp46"

SWEP.TracerParticle = "vietnam_tracer_machinegun_green_primary"

SWEP.TracerRandomness = 6
SWEP.TracerFrequency = 3
