SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_type64p.txt

// Names and basic information
SWEP.PrintName = "Type 64"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "People's Republic of China"
SWEP.SubCategory = "Pistols"
SWEP.Caliber = ".32 ACP"

SWEP.Slot = 1
SWEP.HoldType = "pistol"
SWEP.AimHoldType = "revolver"
SWEP.SprintHoldType = "normal"

SWEP.ViewModel = "models/weapons/mcv/v_type64_pistol.mdl"
SWEP.ViewModelAkimbo = "models/weapons/mcv/v_dual_type64_pistol.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_type64_pistol.mdl"

SWEP.BodyGroups = ""

// Stats

SWEP.DamageGeneric = 22
SWEP.DamageHeadMultiplier = 5
SWEP.DamageChestMultiplier = 1.3
SWEP.DamageStomachMultiplier = 1.25
SWEP.DamageLegMultiplier = 1.05
SWEP.DamageArmMultiplier = 1

SWEP.Num = 1

SWEP.RangeModifier = 0.745

SWEP.Firemodes = {
    MCV.FIREMODE_SEMI
}

SWEP.LastShotAnimation = true
SWEP.NoEjectOnShoot = false

// View slide from recoil
SWEP.ViewSlideRecoilUp = 0.88
SWEP.ViewSlideRecoilRight = 0.36

SWEP.ViewSlideRecoilIronsightUp = 0.76
SWEP.ViewSlideRecoilIronsightRight = 0.32

SWEP.RecoilPushbackValue = 1.5

// Camera shake from recoil
SWEP.ShakeScale = 0.75
SWEP.ShakeFreq = 50
SWEP.ShakeDuration = 0.35

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 0.85
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -1

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(0.06, -2, 0)
SWEP.IronsightAng = Angle(0.2, 0.1, 0)

SWEP.CustomPos = Vector(0, -2, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 5.75
SWEP.SpreadIronsighted = 1.75

SWEP.FireRate = 500 // in rounds per minute

SWEP.CrosshairMinDistance = 4
SWEP.CrosshairDeltaDistance = 4

SWEP.WeaponWeight = 0.91

SWEP.Primary.Ammo = "pistol"
SWEP.Primary.ClipSize = 9
SWEP.Primary.Chamber = 0
SWEP.Primary.DefaultClip = 18
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 22

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 0.95
SWEP.ProneSpreadMultiplier = 0.9
SWEP.StandMoveSpreadMultiplier = 1.1
SWEP.SneakMoveSpreadMultiplier = 1.05
SWEP.CrouchMoveSpreadMultiplier = 1
SWEP.JumpSpreadMultiplier = 1.25

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false
SWEP.HasAkimbo = true

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = false

// Penetration
SWEP.MetalPenetrationDepth = 5
SWEP.GlassPenetrationDepth = 11
SWEP.ConcretePenetrationDepth = 7
SWEP.WoodPenetrationDepth = 15
SWEP.OtherPenetrationDepth = 9

SWEP.MetalDamageModifier = 1.75
SWEP.GlassDamageModifier = 1.35
SWEP.ConcreteDamageModifier = 1.95
SWEP.WoodDamageModifier = 1.45
SWEP.OtherDamageModifier = 1.45

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_Type67.Single"
SWEP.SoundDoubleShot = ""
SWEP.SoundReload = ""
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick_Pistol"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_05"

// Particles (the game's own systems; particles/*.pcf and their materials ship with the addon)
SWEP.MuzzleParticle = "vietnam_muzzleflash_pistol_type2_fp"
SWEP.MuzzleParticleSmoke = "vietnam_muzzleflash_pistol_type2_fp_smoke"
SWEP.MuzzleParticleIronsighted = "vietnam_muzzleflash_pistol_type2_fp_is"
SWEP.MuzzleParticleIronsightedSmoke = "vietnam_muzzleflash_pistol_type2_fp_is_smoke"

SWEP.MuzzleParticle3rdPerson = "vietnam_muzzleflash_pistol_type2_tp"

SWEP.EjectBrassType = 3
SWEP.EjectBrassTrail = "vietnam_weaponeffect_shelleject_trail"
SWEP.EjectBrassParticle = "vietnam_weaponeffect_shelleject_side"

SWEP.TracerParticle = "vietnam_tracer_silenced_green_primary"

SWEP.TracerRandomness = 4
SWEP.TracerFrequency = 1
