SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_xm202.txt

// Names and basic information
SWEP.PrintName = "M202 FLASH"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Anti-Armor"
SWEP.Caliber = "66mm Rocket"

SWEP.Slot = 4
SWEP.HoldType = "rpg"
SWEP.AimHoldType = "rpg"
SWEP.SprintHoldType = "passive"

SWEP.ViewModel = "models/weapons/mcv/v_m202.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_m202.mdl"

SWEP.BodyGroups = ""

// Stats

SWEP.DamageGeneric = 30
SWEP.DamageHeadMultiplier = 1
SWEP.DamageChestMultiplier = 1
SWEP.DamageStomachMultiplier = 1
SWEP.DamageLegMultiplier = 1
SWEP.DamageArmMultiplier = 1

SWEP.Num = 1

SWEP.RangeModifier = 0.95

SWEP.Firemodes = {
    MCV.FIREMODE_SEMI
}

SWEP.LastShotAnimation = false
SWEP.HasEmptyReload = false

// View slide from recoil
SWEP.ViewSlideRecoilUp = 3.12
SWEP.ViewSlideRecoilRight = 0.96

SWEP.ViewSlideRecoilIronsightUp = 2.64
SWEP.ViewSlideRecoilIronsightRight = 0.72

SWEP.RecoilPushbackValue = 1.5

// Camera shake from recoil
SWEP.ShakeScale = 2.5
SWEP.ShakeFreq = 40
SWEP.ShakeDuration = 1

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 0.7
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -0.25

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(0.02, 0, -0.12)
SWEP.IronsightAng = Angle(-0.02, 0.15, 0.2)

SWEP.CustomPos = Vector(0, -2, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 4
SWEP.SpreadIronsighted = 2

SWEP.FireRate = 250 // in rounds per minute

SWEP.CrosshairMinDistance = 8
SWEP.CrosshairDeltaDistance = 4

SWEP.WeaponWeight = 12

SWEP.Primary.Ammo = "rpg_round"
SWEP.Primary.ClipSize = 4
SWEP.Primary.Chamber = 0
SWEP.Primary.DefaultClip = 8
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 25

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 1
SWEP.ProneSpreadMultiplier = 0.75
SWEP.StandMoveSpreadMultiplier = 2
SWEP.SneakMoveSpreadMultiplier = 1.5
SWEP.CrouchMoveSpreadMultiplier = 1.25
SWEP.JumpSpreadMultiplier = 4

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = false

// Penetration
SWEP.MetalPenetrationDepth = 10
SWEP.GlassPenetrationDepth = 10
SWEP.ConcretePenetrationDepth = 10
SWEP.WoodPenetrationDepth = 10
SWEP.OtherPenetrationDepth = 10

SWEP.MetalDamageModifier = 1.25
SWEP.GlassDamageModifier = 1.25
SWEP.ConcreteDamageModifier = 1.25
SWEP.WoodDamageModifier = 1.25
SWEP.OtherDamageModifier = 1.25

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_M202.Single"
SWEP.SoundDoubleShot = ""
SWEP.SoundReload = ""
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_09"

// Particles
SWEP.MuzzleParticle = "muzzleflash_m79"
SWEP.MuzzleParticleSmoke = ""
SWEP.MuzzleParticleIronsighted = "muzzleflash_m79"
SWEP.MuzzleParticleIronsightedSmoke = ""

SWEP.MuzzleParticle3rdPerson = "muzzleflash_m79"

SWEP.EjectBrassType = 0
SWEP.EjectBrassTrail = "shellsmoke"
SWEP.EjectBrassParticle = "port_smoke"

SWEP.TracerParticle = "tracer"

SWEP.TracerRandomness = 6
SWEP.TracerFrequency = 1

SWEP.IconOverride = "entities/mcv_xm202.png"
