// Names for the equipment ammo types (pickup history, weapon info)
language.Add("mcv_grenade_ammo", "Grenades")
language.Add("mcv_molotov_ammo", "Molotov Cocktails")
language.Add("mcv_mine_ammo", "Mines")
language.Add("mcv_explosive_charge_ammo", "Explosive Charges")
language.Add("mcv_flamethrower_fuel_ammo", "Flamethrower Fuel")
language.Add("mcv_crossbowbolt_ammo", "Crossbow Bolts")
language.Add("mcv_flareround_ammo", "Flares")
language.Add("mcv_ammobox_ammo", "Ammo Boxes")
language.Add("mcv_medicbox_ammo", "Medic Boxes")
