"""Compile the PTRD-41 Sniper kitbash with the PTRD rig and separate cartridge."""
import argparse
import json
import re
import shutil
import subprocess
import numpy as np
from bake_ik import load_smd, fk
from pack_paths import asset_path
from build_xm16super import HERE, ROOT, PORT, SCRATCH, relative, rebase, icon

SOURCE = HERE/'MCV_SMD/weapons/v_ptrd41_s/Ref_new.smd'


def viewmodel():
    nodes, frames, _ = load_smd(SOURCE)
    dn, df, _ = load_smd(HERE/'MCV_SMD_OG/weapons/v_ptrd41/Ref_new.smd')
    actual = {name:fk(nodes,frames[0])[i] for i,(name,_) in nodes.items()}
    expected = fk(dn,df[0])
    assert max(np.max(np.abs(actual[name]-expected[i])) for i,(name,_) in dn.items()) < .001
    out = PORT/'v_ptrd41_s'
    out.mkdir(parents=True,exist_ok=True)
    donor = PORT/'v_ptrd41'
    text = rebase((donor/'v_ptrd41.qc').read_text(),donor,out)
    text = text.replace('weapons/mcv/v_ptrd41.mdl','weapons/mcv/v_ptrd41_s.mdl')
    text = re.sub(r'(^\s*studio ")[^"]*Ref_new\.smd"',r'\g<1>'+relative(SOURCE,out)+'"',text,flags=re.M)
    # Keep the PTRD's Ref_Bullet bodygroup and its show/hide animation events.
    text = text.replace('$surfaceprop', '$cdmaterials "models/weapons/mcv/v_vz54/"\n'
                        '$cdmaterials "models/weapons/mcv/optics/"\n\n$surfaceprop',1)
    text = re.sub(r'^// Generated[^\n]*','// KEEP: PTRD-41 Sniper; generated by work/build_ptrd41_sniper.py',text,count=1)
    qc = out/'v_ptrd41_s.qc'
    qc.write_text(text)
    return qc


def worldmodel():
    out = PORT/'w_ptrd41_s'
    out.mkdir(parents=True,exist_ok=True)
    donor = PORT/'w_ptrd41'
    text = rebase((donor/'w_ptrd41.qc').read_text(),donor,out)
    text = text.replace('w_ptrd41.mdl','w_ptrd41_s.mdl')
    text = re.sub(r'\$lod\s+[^\n]+\s*\{[^}]*\}\s*','',text)
    text = re.sub(r'^// Generated[^\n]*','// KEEP: PTRD-41 Sniper world model; original PTRD placement plus scope',text,count=1)
    world_source = HERE/'MCV_SMD_OG/weapons/w_ptrd41/w_ptrd41_lod0.smd'
    wn, wf, _ = load_smd(world_source)
    nodes, frames, _ = load_smd(SOURCE)
    base = next(i for i,(name,_) in nodes.items() if name=='Base')
    mapping = np.eye(4)
    mapping[:3,:3] = np.array([[0,-.85,0],[0,0,.85],[-.85,0,0]])
    mapping[:3,3] = [0,.575,-1.2] # agrees with both PTRD muzzle attachments
    transform = fk(wn,wf[0])[0] @ mapping @ np.linalg.inv(fk(nodes,frames[0])[base])
    normal = transform[:3,:3]/.85
    mesh = SOURCE.read_text().split('triangles\n',1)[1].splitlines()
    lines = world_source.read_text().split('triangles\n',1)[0].rstrip().splitlines()+['triangles']
    for i in range(0,len(mesh)-1,4):
        if mesh[i].strip()=='ptrd41': continue
        lines.append(mesh[i])
        for line in mesh[i+1:i+4]:
            parts = line.split()
            pos = transform @ np.array([*map(float,parts[1:4]),1])
            direction = normal @ np.array(list(map(float,parts[4:7])))
            direction /= max(np.linalg.norm(direction),1e-12)
            lines.append('0 '+' '.join(f'{v:.7f}' for v in [*pos[:3],*direction,*map(float,parts[7:9])])+' 1 0 1')
    lines.append('end')
    (out/'scope.smd').write_text('\n'.join(lines)+'\n')
    text = text.replace('$surfaceprop','$bodygroup "Scope"\n{\n studio "scope.smd"\n}\n'
                        '$cdmaterials "models/weapons/mcv/v_vz54/"\n'
                        '$cdmaterials "models/weapons/mcv/optics/"\n\n$surfaceprop',1)
    qc = out/'w_ptrd41_s.qc'
    qc.write_text(text)
    return qc


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--install',action='store_true')
    args = parser.parse_args()
    compiler = ROOT.parents[2]/'bin/studiomdl.exe'
    logs = HERE/'ptrd41_sniper_build'
    logs.mkdir(exist_ok=True)
    results = []
    for qc in [viewmodel(),worldmodel()]:
        run = subprocess.run([str(compiler),'-game',str(SCRATCH),'-nop4',str(qc)],cwd=compiler.parent,
                             capture_output=True,text=True,timeout=300)
        output = run.stdout+run.stderr
        (logs/(qc.stem+'.log')).write_text(output)
        if run.returncode or 'Completed' not in output or 'ERROR:' in output:
            raise RuntimeError(output[-6500:])
        files = sorted((SCRATCH/'models/weapons/mcv').glob(qc.stem+'.*'))
        assert any(p.suffix=='.mdl' for p in files)
        if args.install:
            for file in files: shutil.copy2(file,asset_path('models/weapons/mcv/'+file.name))
        results.append(dict(model=qc.stem,installed=args.install,files=[p.name for p in files]))
        print(qc.stem,'compiled',len(files),'files',flush=True)
    if args.install: icon(SOURCE,'ptrd_sniper')
    (logs/'build.json').write_text(json.dumps(results,indent=2)+'\n')


if __name__=='__main__': main()
