"""Extract hammer event cycles from the compiled viewmodels, without rebuilding weapons.

python work/build_hammer_events.py [--output PATH]
The generated data lets gameplay schedule the model's event on a predicted clock;
render-time FireAnimationEvent remains responsible only for cosmetic effects.
MDL v48/v49 studiohdr_t, mstudioseqdesc_t (212 bytes), mstudioevent_t (80 bytes).
"""
import argparse
import json
from pathlib import Path
import struct
from pack_paths import mounted_files

ROOT = Path(__file__).resolve().parents[1]


def read_events(path):
    data = path.read_bytes()
    def integer(off):
        return struct.unpack_from("<i", data, off)[0]
    def string(off):
        return data[off:data.index(b"\0", off)].decode("ascii")
    if data[:4] != b"IDST" or integer(4) not in (48, 49):
        raise ValueError(f"unsupported MDL: {path}")
    count, offset = struct.unpack_from("<ii", data, 188)
    result = {}
    for i in range(count):
        seq = offset + i * 212
        name = string(seq + integer(seq + 4)).lower()
        n, start = struct.unpack_from("<ii", data, seq + 24)
        events = {}
        for j in range(n):
            event = seq + start + j * 80
            options = data[event + 12:event + 76].split(b"\0", 1)[0]
            if options not in (b"hammerpos 0", b"hammerpos 1"):
                continue
            cycle = struct.unpack_from("<f", data, event)[0]
            if not 0 <= cycle <= 1:
                raise ValueError(f"invalid event cycle in {path}: {name}")
            value = int(options[-1:])
            events[value] = min(events.get(value, 1), cycle)
        if events:
            result[name] = events
    return result


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output", type=Path, default=ROOT / "lua/mcv/shared/sh_hammer_events.lua")
    a = p.parse_args()
    lines = ["// Generated by work/build_hammer_events.py from the shipped MDLs.",
             "// Normalized event cycles, keyed by model, sequence and hammer position.",
             "MCV.HammerEvents = {"]
    models = sequences = 0
    for path in sorted(mounted_files("models/weapons/mcv", "v_*.mdl"), key=lambda p:p.name):
        events = read_events(path)
        if not events:
            continue
        models += 1
        sequences += len(events)
        lines.append(f'    [{json.dumps("models/weapons/mcv/" + path.name)}] = {{')
        for name, values in sorted(events.items()):
            fields = ", ".join(f"[{k}] = {v:.8g}" for k, v in sorted(values.items()))
            lines.append(f"        [{json.dumps(name)}] = {{{fields}}},")
        lines.append("    },")
    lines += ["}", ""]
    a.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"{models} models, {sequences} sequences -> {a.output}")


if __name__ == "__main__":
    main()
