"""Create the new variant once, leaving the hand-tuned M16 untouched."""
from pack_paths import PART2

source = PART2 / 'lua/weapons/mcv_m16a1.lua'
target = PART2 / 'lua/weapons/mcv_m16_flamer.lua'
if target.exists():
    raise SystemExit('Variant already exists; edit it directly.')
text = source.read_text()
text = text.replace('SWEP.Spawnable = true', 'SWEP.Spawnable = false // Incomplete; development only.\nSWEP.NPCUsable = false')
text = text.replace('SWEP.Base = "mcv_base"', 'SWEP.Base = "mcv_underbarrel_flame"')
text = text.replace('SWEP.PrintName = "M16A1"', 'SWEP.PrintName = "M16 Flamer"')
text = text.replace('v_m16a1.mdl', 'v_m16_flamer.mdl').replace('w_m16a1.mdl', 'w_m16_flamer.mdl')
text = text.replace('SWEP.HasBayonet = true', 'SWEP.HasBayonet = false')
text = text.replace('// Generated by work/port_weapon.py from cscripts/weapon_m16a1.txt',
                    '// Estimated variant: standard M16 rifle with a single-cartridge underbarrel flame burst.')
text += '''
SWEP.HasRifleGrenade = true
SWEP.RifleGrenadeIsUBGL = true
SWEP.Secondary.Ammo = "mcv_flame_cartridge"
SWEP.Secondary.ClipSize = 1
SWEP.Secondary.DefaultClip = 4
SWEP.Secondary.Automatic = false
SWEP.IconOverride = "entities/mcv_m16_flamer.png"
SWEP.MovementPoseWalk = 134
SWEP.MovementPoseSprint = 229
SWEP.MovementPoseSighted = 134
SWEP.SafeMovementAnimations = true
'''
target.write_text(text)
print(target)
