"""Import MCV's standalone bullet decals without replacing global game materials."""
from pathlib import Path
import argparse
import re
from vpklib import VPK

ROOT = Path(__file__).resolve().parents[1]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--game', type=Path, default=Path('D:/SteamLibrary/steamapps/common/Military Conflict - Vietnam/vietnam'))
    args = ap.parse_args()
    vpk = VPK(str(args.game/'pak01_dir.vpk'))
    text = vpk.read('scripts/decals_subrect.txt').decode()
    groups = {}
    for name, body in re.findall(r'"Impact\.([^"\n]+)"\s*\{([^}]+)\}', text):
        if name in ('Flesh', 'GreenFlesh', 'OrangeFlesh', 'MetalShield'):
            continue
        paths = re.findall(r'"(decals[^"\n]+)"\s*"\d+"', body, re.I)
        paths = [p.lower().replace('\\', '/').replace('_subrect', '') for p in paths]
        if paths:
            groups[name.lower()] = paths
    files = set()
    for paths in groups.values():
        for path in paths:
            src = 'materials/'+path+'.vmt'
            material = vpk.read(src).decode().replace('\r', '')
            def texture(match):
                old = match[1].lower().replace('\\', '/')
                source = 'materials/'+old+'.vtf'
                target = ROOT/'materials/mcv'/ (old+'.vtf')
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(vpk.read(source))
                files.add(target)
                return '$basetexture "mcv/'+old+'"'
            material, count = re.subn(r'\$basetexture\s+"([^"\n]+)"', texture, material, flags=re.I)
            assert count == 1, path
            # The original standalone shader works in GMod; avoid MCV's atlas Subrect shader.
            assert material.strip().startswith('DecalModulate'), path
            target = ROOT/'materials/mcv'/(path+'.vmt')
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(material)
            files.add(target)
    lua = ['// Generated by work/import_impact_decals.py from MCV decals_subrect.txt.',
           '// Standalone materials preserve original textures and decal scale.',
           'MCV.SurfaceDecals = {']
    for name, paths in sorted(groups.items()):
        lua.append('    '+name+' = {'+', '.join('"mcv/'+p+'"' for p in paths)+'},')
    lua += ['}', '', 'for family, materials in pairs(MCV.SurfaceDecals) do',
            '    game.AddDecal("MCV.Impact." .. family, materials)', 'end', '']
    (ROOT/'lua/mcv/shared/sh_impact_decals.lua').write_text('\n'.join(lua))
    print('Imported', len(files), 'files,', len(groups), 'decal families,', sum(p.stat().st_size for p in files), 'bytes')
    vpk.close()


if __name__ == '__main__':
    main()
