"""Validate the complete staged safety rollout, then install across the two content packs.

Run build_safe_movement.py --compile first. No game is launched.
"""
import json
from pathlib import Path
import shutil

from build_safe_movement import WORK, OUT, PORT, BEGIN, END, ACTS, digest, weapon_models, verify_timings
from fix_gyrojet_sprint import model_metadata
from pack_paths import asset_path, mounted_files
from port_qc import QC

EXTENSIONS = ('.mdl', '.vvd', '.dx80.vtx', '.dx90.vtx')
BUNDLES = ('v_m635', 'v_xm16super', 'v_ptrd41_s')


def sync_bundle(name):
    folder = WORK / 'MCV_SMD/weapons' / name
    target = folder / (name + '.qc')
    source = (PORT / name / target.name).read_text()
    raw = target.read_text()
    backup = OUT / 'before_bundles' / target.name
    backup.parent.mkdir(parents=True, exist_ok=True)
    if not backup.exists():
        backup.write_text(raw)
    if BEGIN in raw:
        a, rest = raw.split(BEGIN, 1)
        _, b = rest.split(END, 1)
        raw = a + b
    qc = QC(raw)
    sequences = [s for s in QC(source).blocks('sequence') if s.activity() in ACTS]
    for sequence in sequences:
        old = qc.find('sequence', sequence.name)
        assert old, (name, sequence.name)
        raw = raw.replace(old.render(), sequence.render(), 1)
    definitions = BEGIN + source.split(BEGIN, 1)[1].split(END, 1)[0] + END
    marker = '$sequence "' + sequences[0].name + '"'
    raw = raw.replace(marker, definitions + marker, 1)
    target.write_text(raw, newline='\n')
    shutil.copytree(PORT / name / 'safe_anims', folder / 'safe_anims', dirs_exist_ok=True)
    manifest_path = folder / 'compile-manifest.json'
    manifest = json.loads(manifest_path.read_text())
    for file in (folder / 'safe_anims').glob('*.smd'):
        manifest[file.relative_to(folder).as_posix()] = digest(file)
    manifest[target.name] = digest(target)
    manifest_path.write_text(json.dumps(manifest, indent=2) + '\n')


def main():
    names = sorted({p.stem for p in mounted_files('models/weapons/mcv', 'v_*.mdl')} & weapon_models()[0])
    pending, rows = [], []
    for name in names:
        report_path = OUT / 'models' / (name + '.json')
        report = json.loads(report_path.read_text())
        assert not report.get('error') and report.get('compile', {}).get('ok'), name
        assert report['qc_sha256'] == digest(PORT / name / (name + '.qc')), (name, 'QC changed since bake')
        assert not report.get('safe') or name in weapon_models()[1], (name, 'equipment accidentally baked')
        old = asset_path('models/weapons/mcv/' + name + '.mdl')
        compiled = WORK / 'compile_test_game/models/weapons/mcv' / (name + '.mdl')
        before, after = model_metadata(old), model_metadata(compiled)
        assert before['sequences'] == after['sequences'], (name, 'events/activities')
        timing = verify_timings(name, before, after)
        row = {'model': name, 'safe': report.get('safe', False), 'files': {}, 'timing_check': timing}
        for ext in EXTENSIONS:
            src = compiled.with_name(name + ext)
            dst = asset_path('models/weapons/mcv/' + src.name)
            assert src.is_file() and src.stat().st_size, src
            row['files'][str(dst)] = digest(src)
            pending.append((src, dst))
        rows.append(row)
    # Every used viewmodel must pass before any model or the runtime opt-in is installed.
    for src, dst in pending:
        shutil.copy2(src, dst)
        assert digest(src) == digest(dst), dst
        if src.name.split('.')[0] in BUNDLES:
            bundled = WORK / 'MCV_SMD/weapons' / src.name.split('.')[0] / 'compiled/models/weapons/mcv' / src.name
            shutil.copy2(src, bundled)
    for name in BUNDLES:
        sync_bundle(name)
    manifest = WORK.parent / 'lua/mcv/shared/sh_safe_movement.lua'
    manifest.write_text('// Generated by work/install_safe_movement.py after model validation.\n'
                        'MCV.SafeMovementModels = {\n' + ''.join(
                            '    ["models/weapons/mcv/' + r['model'] + '.mdl"] = true,\n'
                            for r in rows if r['safe']) + '}\n', newline='\n')
    (OUT / 'installed.json').write_text(json.dumps(rows, indent=2) + '\n')
    print(f"Installed {len(rows)} viewmodels; {sum(r['safe'] for r in rows)} safety movement opt-ins.")


if __name__ == '__main__':
    main()
