SWEP.Base = "mcv_melee"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_crowbar.txt

// Names and basic information
SWEP.PrintName = "Crowbar"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Black Mesa"
SWEP.SubCategory = "Melee"

SWEP.Slot = 0

SWEP.ViewModel = "models/weapons/mcv/v_crowbar.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_crowbar.mdl"
SWEP.MovementPoseWalk = 167
SWEP.MovementPoseSprint = 268

SWEP.HoldType = "melee"
SWEP.AimHoldType = "melee"

SWEP.DamageGeneric = 25
SWEP.MeleeRange = 48
SWEP.MeleeRangeAlt = 64
SWEP.SlashRate = 150

SWEP.CanThrow = false

SWEP.SoundHitFlesh = "MCV_Weapon_M1942.Stab"
SWEP.SoundHitWorld = "MCV_Weapon_M1942.Hit"
SWEP.SoundThrustFlesh = "MCV_Weapon_M1942.ThrustStab"
SWEP.SoundThrustWorld = "MCV_Weapon_M1942.ThrustHit"

SWEP.WeaponWeight = 1
