SWEP.Base = "mcv_melee"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_wrench.txt

// Names and basic information
SWEP.PrintName = "Wrench"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = ""
SWEP.SubCategory = "Melee"

SWEP.Slot = 0

SWEP.ViewModel = "models/weapons/mcv/v_wrench.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_wrench.mdl"
SWEP.MovementPoseWalk = 167
SWEP.MovementPoseSprint = 268

SWEP.HoldType = "melee"
SWEP.AimHoldType = "melee"

SWEP.DamageGeneric = 40
SWEP.MeleeRange = 48
SWEP.MeleeRangeAlt = 56
SWEP.SlashRate = 75

SWEP.CanThrow = false
SWEP.CanRepair = true

SWEP.SoundHitFlesh = "MCV_Weapon_M1942.Stab"
SWEP.SoundHitWorld = "MCV_Weapon_M1942.Hit"
SWEP.SoundThrustFlesh = "MCV_Weapon_M1942.ThrustStab"
SWEP.SoundThrustWorld = "MCV_Weapon_M1942.ThrustHit"

SWEP.WeaponWeight = 5
