SWEP.Base = "mcv_melee"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_sickle.txt

// Names and basic information
SWEP.PrintName = "Sickle"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Vietnam"
SWEP.SubCategory = "Melee"

SWEP.Slot = 0

SWEP.ViewModel = "models/weapons/mcv/v_sickle.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_sickle.mdl"
SWEP.MovementPoseWalk = 167
SWEP.MovementPoseSprint = 268


SWEP.DamageGeneric = 42
SWEP.MeleeRange = 56
SWEP.MeleeRangeAlt = 64
SWEP.SlashRate = 150

SWEP.CanThrow = true

SWEP.SoundHitFlesh = "MCV_Weapon_M1942.Stab"
SWEP.SoundHitWorld = "MCV_Weapon_M1942.Hit"
SWEP.SoundThrustFlesh = "MCV_Weapon_M1942.ThrustStab"
SWEP.SoundThrustWorld = "MCV_Weapon_M1942.ThrustHit"

SWEP.WeaponWeight = 1
