SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_vcshotgun.txt

// Names and basic information
SWEP.PrintName = "Homemade Shotgun"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Vietnam"
SWEP.SubCategory = "Shotguns"
SWEP.Caliber = "12 Gauge Shell"

SWEP.Slot = 2
SWEP.HoldType = "shotgun"
SWEP.AimHoldType = "shotgun"
SWEP.SprintHoldType = "passive"

SWEP.ViewModel = "models/weapons/mcv/v_vcshotgun.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_vcshotgun.mdl"

SWEP.BodyGroups = ""
SWEP.MagInTime = 1.2
SWEP.MagInTimeEmpty = 1.2

// Stats

SWEP.DamageGeneric = 27
SWEP.DamageHeadMultiplier = 2.5
SWEP.DamageChestMultiplier = 1.5
SWEP.DamageStomachMultiplier = 1.25
SWEP.DamageLegMultiplier = 0.9
SWEP.DamageArmMultiplier = 0.85

SWEP.Num = 5

SWEP.RangeModifier = 0.805

SWEP.Firemodes = {
    MCV.FIREMODE_SEMI
}

SWEP.LastShotAnimation = false
SWEP.NoEjectOnShoot = true

// View slide from recoil
SWEP.ViewSlideRecoilUp = 3
SWEP.ViewSlideRecoilRight = 0.84

SWEP.ViewSlideRecoilIronsightUp = 2.24
SWEP.ViewSlideRecoilIronsightRight = 0.64

SWEP.RecoilPushbackValue = 1.5

// Camera shake from recoil
SWEP.ShakeScale = 3
SWEP.ShakeFreq = 30
SWEP.ShakeDuration = 0.6

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 1
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -0.25
SWEP.MovementPoseWalk = 148
SWEP.MovementPoseSprint = 244
SWEP.MovementPoseSighted = 148

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(0, 0, 0)
SWEP.IronsightAng = Angle(0, 0, 0)

SWEP.CustomPos = Vector(0, 0, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 8.25
SWEP.SpreadIronsighted = 2.75

SWEP.FireRate = 300 // in rounds per minute

SWEP.CrosshairMinDistance = 6
SWEP.CrosshairDeltaDistance = 8

SWEP.WeaponWeight = 3.2

SWEP.Primary.Ammo = "buckshot"
SWEP.Primary.ClipSize = 1
SWEP.Primary.Chamber = 0
SWEP.Primary.DefaultClip = 20
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 50

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 1
SWEP.ProneSpreadMultiplier = 1
SWEP.StandMoveSpreadMultiplier = 1
SWEP.SneakMoveSpreadMultiplier = 1
SWEP.CrouchMoveSpreadMultiplier = 1
SWEP.JumpSpreadMultiplier = 1

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = false

// Penetration
SWEP.MetalPenetrationDepth = 3
SWEP.GlassPenetrationDepth = 8
SWEP.ConcretePenetrationDepth = 5
SWEP.WoodPenetrationDepth = 13
SWEP.OtherPenetrationDepth = 6

SWEP.MetalDamageModifier = 1.7
SWEP.GlassDamageModifier = 1.3
SWEP.ConcreteDamageModifier = 1.9
SWEP.WoodDamageModifier = 1.4
SWEP.OtherDamageModifier = 1.4

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_VCShotgun.Single"
SWEP.SoundDoubleShot = "MCV_Weapon_VCShotgun.Single"
SWEP.SoundReload = ""
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_09"

// Particles (the game's own systems; particles/*.pcf and their materials ship with the addon)
SWEP.MuzzleParticle = "vietnam_muzzleflash_shotgun_type1_fp"
SWEP.MuzzleParticleSmoke = "vietnam_muzzleflash_shotgun_type1_fp_smoke"
SWEP.MuzzleParticleIronsighted = "vietnam_muzzleflash_shotgun_type1_fp_is"
SWEP.MuzzleParticleIronsightedSmoke = "vietnam_muzzleflash_shotgun_type1_fp_is_smoke"

SWEP.MuzzleParticle3rdPerson = "vietnam_muzzleflash_shotgun_type1_tp"

SWEP.EjectBrassType = 2
SWEP.EjectBrassTrail = "vietnam_weaponeffect_shelleject_trail"
SWEP.EjectBrassParticle = "vietnam_weaponeffect_shelleject_side"

SWEP.TracerParticle = "vietnam_tracer_shotgun_green_primary"

SWEP.TracerRandomness = 6
SWEP.TracerFrequency = 1
