SWEP.Base = "mcv_melee"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_katana.txt

// Names and basic information
SWEP.PrintName = "Katana"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Empire of Japan"
SWEP.SubCategory = "Melee"

SWEP.Slot = 0

SWEP.ViewModel = "models/weapons/mcv/v_katana.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_katana.mdl"
SWEP.MovementPoseWalk = 157
SWEP.MovementPoseSprint = 255


SWEP.DamageGeneric = 45
SWEP.DamageGenericAlt = 90
SWEP.MeleeRange = 64
SWEP.MeleeRangeAlt = 72
SWEP.SlashRate = 120

SWEP.CanThrow = false

SWEP.SoundHitFlesh = "MCV_Weapon_Katana.HitFlesh"
SWEP.SoundHitWorld = "MCV_Weapon_Katana.Hit"
SWEP.SoundThrustFlesh = "MCV_Weapon_Katana.ThrustHitFlesh"
SWEP.SoundThrustWorld = "MCV_Weapon_Katana.ThrustHit"

SWEP.WeaponWeight = 1
