SWEP.Base = "mcv_throwable"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_css.txt

// Names and basic information
SWEP.PrintName = "RGD-1 Smoke"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Soviet Union"
SWEP.SubCategory = "Grenades"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_css.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_css.mdl"
SWEP.MovementPoseWalk = 159
SWEP.MovementPoseSprint = 258
SWEP.ThrowModel = "models/weapons/mcv/w_css_ignited.mdl"

SWEP.ThrowEntity = "mcv_grenade_smoke"
SWEP.FuseModes = {3, 5}
SWEP.HasUnderhand = true

SWEP.ExplosionDamage = 0
SWEP.ExplosionRadius = 500
SWEP.SmokeColor = Vector(53, 53, 51)

SWEP.Primary.Ammo = "mcv_grenade"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 2

SWEP.WeaponWeight = 1
