SWEP.Base = "mcv_throwable"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_csg2.txt

// Names and basic information
SWEP.PrintName = "Type 67 HE Grenade"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "People's Republic of China"
SWEP.SubCategory = "Grenades"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_csg2.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_csg2.mdl"
SWEP.MovementPoseWalk = 159
SWEP.MovementPoseSprint = 258

SWEP.ThrowEntity = "mcv_grenade_frag"
SWEP.FuseModes = {3, 5}
SWEP.HasUnderhand = true

SWEP.ExplosionDamage = 225
SWEP.ExplosionRadius = 250

SWEP.Primary.Ammo = "mcv_grenade"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 2

SWEP.WeaponWeight = 1
