SWEP.Base = "mcv_placeable"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_dynamite.txt

// Names and basic information
SWEP.PrintName = "Dynamite"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "People's Republic of China"
SWEP.SubCategory = "Explosives"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_dynamite.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_dynamite.mdl"
SWEP.MovementPoseWalk = 128
SWEP.MovementPoseSprint = 221
SWEP.MovementPoseSighted = 128

SWEP.PlaceKind = "dynamite"
SWEP.PlacedEntityClass = "mcv_placed_dynamite"
SWEP.ExplosionDamage = 500
SWEP.ExplosionRadius = 550

SWEP.Primary.Ammo = "mcv_explosive_charge"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 1

SWEP.WeaponWeight = 5

SWEP.PlacedAngleOffset = Angle(90, 0, 90)