SWEP.Base = "mcv_melee"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_type30_bayonet.txt

// Names and basic information
SWEP.PrintName = "Type 30 Bayonet"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Empire of Japan"
SWEP.SubCategory = "Melee"

SWEP.Slot = 0

SWEP.ViewModel = "models/weapons/mcv/v_type30_bayonet.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_type30_bayonet.mdl"
SWEP.MovementPoseWalk = 167
SWEP.MovementPoseSprint = 268


SWEP.DamageGeneric = 55
SWEP.DamageGenericAlt = 75
SWEP.MeleeRange = 48
SWEP.MeleeRangeAlt = 64
SWEP.SlashRate = 150

SWEP.CanThrow = true

SWEP.SoundHitFlesh = "MCV_Weapon_AK47_Bayonet.Stab"
SWEP.SoundHitWorld = "MCV_Weapon_AK47_Bayonet.Hit"
SWEP.SoundThrustFlesh = "MCV_Weapon_AK47_Bayonet.ThrustStab"
SWEP.SoundThrustWorld = "MCV_Weapon_AK47_Bayonet.ThrustHit"

SWEP.WeaponWeight = 0
