SWEP.Base = "mcv_melee"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_fists.txt

// Names and basic information
SWEP.PrintName = "Fists"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = ""
SWEP.SubCategory = "Melee"

SWEP.Slot = 0

SWEP.ViewModel = "models/weapons/mcv/v_fist.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_fist.mdl"
SWEP.MovementPoseWalk = 167
SWEP.MovementPoseSprint = 268

SWEP.HoldType = "fist"
SWEP.AimHoldType = "fist"

SWEP.DamageGeneric = 20
SWEP.MeleeRange = 32
SWEP.MeleeRangeAlt = 42
SWEP.SlashRate = 150

SWEP.CanThrow = false

SWEP.SoundHitFlesh = "MCV_Weapon_Fists.Punch"
SWEP.SoundHitWorld = "MCV_Weapon_Fists.PunchWall"
SWEP.SoundThrustFlesh = "MCV_Weapon_Fists.PowerPunch"
SWEP.SoundThrustWorld = "MCV_Weapon_Fists.PowerPunchWall"

SWEP.WeaponWeight = 0
